Use LargeBytes in test to fix compilation warning with g++ 9.x
Platform009 updated the gcc version which caused a compilation error when building in Release.

```
[340/424] Building CXX object CMakeFiles/runtime-tests.dir/runtime/bytearray-builtins-test.cpp.o
FAILED: CMakeFiles/runtime-tests.dir/runtime/bytearray-builtins-test.cpp.o
/data/users/lorenarthur/fbsource/fbcode/pyro/gcc_build/g++  -I../ext/Internal -I../third-party/benchmark-1.5.1/src/../include -I../third-party/googletest/googlemock/include -I../third-party/googletest/googlemock -I../third-party/googletest/googletest/include -I../third-party/googletest/googletest -I../runtime -I../capi -Ibootstrap -O3 -DNDEBUG -march=corei7 -mtune=core-avx2 -mpclmul -fPIC -fvisibility=hidden -Wall -Werror -Wextra -Wno-missing-braces -Wno-missing-field-initializers -Wpedantic -Wshadow -fno-exceptions -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-rtti -std=c++11 -MD -MT CMakeFiles/runtime-tests.dir/runtime/
bytearray-builtins-test.cpp.o -MF CMakeFiles/runtime-tests.dir/runtime/bytearray-builtins-test.cpp.o.d -o CMakeFiles/runtime-tests.dir/runtime/bytearray-builtins-test.cpp.o -c ../runtime/bytearray-builtins-test.cpp
In file included from ../runtime/handles-decl.h:3,
                 from ../runtime/handles.h:3,
                 from ../runtime/bytecode.h:3,
                 from ../runtime/runtime.h:3,
                 from ../runtime/bytearray-builtins.h:3,
                 from ../runtime/bytearray-builtins-test.cpp:1:
../runtime/objects.h: In member function ‘virtual void py::testing::BytearrayBuiltinsTest_MaketransWithNonEmptyReturnsBytes_Test::TestBody()’:
../runtime/objects.h:4908:35: error: array subscript 98 is outside array bounds of ‘py::RawSmallBytes [1]’ [-Werror=array-bounds]
 4908 |   return smallDataData(this)[index];
      |                                   ^
../runtime/objects.h:4557:37: note: while referencing ‘<anonymous>’
 4557 |     return RawSmallBytes::cast(*this).byteAt(index);
      |                                     ^
../runtime/objects.h:4908:35: error: array subscript 99 is outside array bounds of ‘py::RawSmallBytes [1]’ [-Werror=array-bounds]
 4908 |   return smallDataData(this)[index];
      |                                   ^
../runtime/objects.h:4557:37: note: while referencing ‘<anonymous>’
 4557 |     return RawSmallBytes::cast(*this).byteAt(index);
      |                                     ^
../runtime/objects.h:4908:35: error: array subscript 100 is outside array bounds of ‘py::RawSmallBytes [1]’ [-Werror=array-bounds]
 4908 |   return smallDataData(this)[index];
      |                                   ^
../runtime/objects.h:4557:37: note: while referencing ‘<anonymous>’
 4557 |     return RawSmallBytes::cast(*this).byteAt(index);
      |                                     ^
cc1plus: all warnings being treated as errors
[354/424] Building CXX object CMakeFiles/runtime-tests.dir/runtime/bytes-builtins-test.cpp.o
FAILED: CMakeFiles/runtime-tests.dir/runtime/bytes-builtins-test.cpp.o
/data/users/lorenarthur/fbsource/fbcode/pyro/gcc_build/g++  -I../ext/Internal -I../third-party/benchmark-1.5.1/src/../include -I../third-party/googletest/googlemock/include -I../third-party/googletest/googlemock -I../third-party/googletest/googletest/include -I../third-party/googletest/googletest -I../runtime -I../capi -Ibootstrap -O3 -DNDEBUG -march=corei7 -mtune=core-avx2 -mpclmul -fPIC -fvisibility=hidden -Wall -Werror -Wextra -Wno-missing-braces -Wno-missing-field-initializers -Wpedantic -Wshadow -fno-exceptions -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-rtti -std=c++11 -MD -MT CMakeFiles/runtime-tests.dir/runtime/
bytes-builtins-test.cpp.o -MF CMakeFiles/runtime-tests.dir/runtime/bytes-builtins-test.cpp.o.d -o CMakeFiles/runtime-tests.dir/runtime/bytes-builtins-test.cpp.o -c ../runtime/bytes-builtins-test.cpp
In file included from ../runtime/bytes-builtins.h:3,
                 from ../runtime/bytes-builtins-test.cpp:1:
../runtime/objects.h: In member function ‘virtual void py::testing::BytesBuiltinsTest_MaketransWithNonEmptyReturnsBytes_Test::TestBody()’:
../runtime/objects.h:4908:35: error: array subscript 98 is outside array bounds of ‘py::RawSmallBytes [1]’ [-Werror=array-bounds]
 4908 |   return smallDataData(this)[index];
      |                                   ^
../runtime/objects.h:4557:37: note: while referencing ‘<anonymous>’
 4557 |     return RawSmallBytes::cast(*this).byteAt(index);
      |                                     ^
../runtime/objects.h:4908:35: error: array subscript 99 is outside array bounds of ‘py::RawSmallBytes [1]’ [-Werror=array-bounds]
 4908 |   return smallDataData(this)[index];
      |                                   ^
../runtime/objects.h:4557:37: note: while referencing ‘<anonymous>’
 4557 |     return RawSmallBytes::cast(*this).byteAt(index);
      |                                     ^
../runtime/objects.h:4908:35: error: array subscript 100 is outside array bounds of ‘py::RawSmallBytes [1]’ [-Werror=array-bounds]
 4908 |   return smallDataData(this)[index];
      |                                   ^
../runtime/objects.h:4557:37: note: while referencing ‘<anonymous>’
 4557 |     return RawSmallBytes::cast(*this).byteAt(index);
      |                                     ^
cc1plus: all warnings being treated as errors
```

Based on Facebook D27308878