Fix clang-tidy Python.h not found error
Currently, changes in some C Extension files would cause a clang-tidy error (i.e. `pyro/ext/Python/pythonrun-test.cpp:3:10: error: 'Python.h' file not found [clang-diagnostic-error]`)

The fix was to add `C_API_HEADERS_OUTPUT` (which includes `Python.h`) to `cpython-sources` which is used by clang-tidy to find all the header files for its analysis.

Based on Facebook D19331104